[package]
name = "QR2M"
description = "Quantum Random Rust Mnemonic"
version = "0.74.0"
authors = ["Control Owl <qr2m[at]r-o0-t[dot]wtf>"]
license-file = "LICENSE.txt"
repository = "https://github.com/control-owl/qr2m"
readme = "README.md"
edition = "2021"
build = "build.rs"


[dependencies]
rust-i18n = "3.1.3"     # Multi-language support    
toml = "0.8.20"         # Settings                  
serde = "1.0.218"       # App settings              
toml_edit = "0.22.24"   # Config file               
serde_json = "1.0.139"  # ANU API                   
csv = "1.3.1"           # Coin database             
rand = "0.9.0"          # Random number generator   
sha2 = "0.10.8"         # Entropy checksum          
hex = "0.4.3"           # Seed                      
bip39 = "2.1.0"         # Mnemonic                  
regex = "1.11.1"        # Parsing derivation path   
secp256k1 = "0.30.0"    # Extended keys             
bs58 = "0.5.1"          # Extended keys             
ripemd = "0.1.3"        # Addresses derivation      
num-bigint = "0.4.6"    # Child keys                
sha3 = "0.10"           # keccak addresses          
gtk4 = "0.9.6"          # GUI GTK4                  
glib = "0.20.9"         # GUI                       
libadwaita = "0.7.1"    # GUI Theme                 
lazy_static = "1.5.0"   # Multithreading            
include_dir = "0.7.4"   # Embedded resources        
once_cell = "1.20.3"    # Static resources          
dashmap = "6.1.0"       # Address generation        

# Testing
ed25519-dalek = "2.1.1" # Solana                    
tokio = { version = "1.43.0", features = ["full"] } 
reqwest = { version = "0.12.12", features = ["json"] }
native-tls = "0.2.14"


[build-dependencies]    # Windows
winres = "0.1.12"       # exe icon and description  


[package.metadata.winres]
OriginalFilename = "QR2M.EXE"
LegalCopyright = "Copyright © 2023-2025 Control Owl"
FileDescription = "Quantum Random Rust Mnemonic"


[package.metadata.excluded]
exclude = ["build.rs"]


[[bin]]
name = "QR2M"
path = "src/main.rs"


[lib]
name = "qr2m_lib"
path = "src/lib.rs"