[package]
name = "QR2M"
description = "Quantum Random Rust Mnemonic"
version = "0.3.0"
authors = ["Control Owl <qr2m[at]r-o0-t[dot]wtf>"]
readme = "README.md"
edition = "2021"


# Crate                 # Internal function
[dependencies]
rand = "0.8.5"          # Random number generator   
sha2 = "0.10.8"         # Entropy checksum          
hex = "0.4.3"           # Seed                      
csv = "1.3.0"           # BIP44 coin_types          
bip39 = "2.0.0"         # Mnemonic                  
bitcoin = "0.31.0"      # Derivation path           
gtk4 = "0.8.0"          # GUI GTK4                  
glib = "0.19.0"         # GUI                       


# TESTING



[[bin]]
name = "QR2M"
path = "src/main.rs"

[workspace]

[package.metadata.docs.rs]
targets = ["src/main.rs", "src/error_handler.rs", "src/converters.rs"]