[package]
name = "QR2M"
description = "Quantum Random Rust Mnemonic"
version = "0.21.0"
authors = ["Control Owl <qr2m[at]r-o0-t[dot]wtf>"]
# copyright = "Copyright © 2023-2024 D3BUG"
license-file = "LICENSE.txt"
repository = "https://github.com/control-owl/qr2m"
readme = "README.md"
edition = "2021"


[dependencies]
# Basic                 # Internal function
rust-i18n = "3.0.1"     # Multi-language support    
toml = "0.8.12"         # Settings                  
serde_json = "1.0.114"  # ANU API                   
lazy_static = "1.4.0"   # Wallet keys               
csv = "1.3.0"           # Coin database             


# Derivation
rand = "0.8.5"          # Random number generator   
sha2 = "0.10.8"         # Entropy checksum          
hex = "0.4.3"           # Seed                      
bip39 = "2.0.0"         # Mnemonic                  
regex = "1.10.3"        # Parsing derivation path   
secp256k1 = "0.29.0"    # Extended keys             
bs58 = "0.5.0"          # Extended keys             
ripemd = "0.1.3"        # Addresses derivation      
num-bigint = "0.4"      # Child keys                
sha3 = "0.10"           # keccak addresses          

# GUI
# BUG in gtk4 crate Version >0.8.0
gtk4 = "0.8.0"          # GUI GTK4                  
glib = "0.19.7"         # GUI                       
libadwaita = "0.6.0"    # GUI Theme                 




# Testing
ed25519-dalek = "2.1.1"   # Solana

[[bin]]
name = "QR2M"
path = "src/main.rs"

[lib]
name = "qr2m_lib"
path = "src/lib.rs"