[package]
name = "QR2M"
description = "Quantum Random Rust Mnemonic"
version = "0.2.0"
authors = ["Control Owl <qr2m[at]r-o0-t[dot]wtf>"]
readme = "README.md"
edition = "2021"


[dependencies]
# Default
rand = "0.8.5"
sha2 = "0.10.8"
hex = "0.4.3"
bip39 = "2.0.0"
structopt = "0.3.26"
thiserror = "1.0.51"
bitcoin = "0.31.0"
csv = "1.3.0"

# Testing


[[bin]]
name = "QR2M"
path = "src/main.rs"

[workspace]

[package.metadata.docs.rs]
targets = ["src/main.rs", "src/error_handler.rs", "src/converters.rs"]