[package]
name = "QR2M"
description = "Quantum Random Rust Mnemonic"
version = "0.60.1"
authors = ["Control Owl <qr2m[at]r-o0-t[dot]wtf>"]
# copyright = "Copyright © 2023-2024 Control Owl"
license-file = "LICENSE.txt"
repository = "https://github.com/control-owl/qr2m"
readme = "README.md"
edition = "2021"
build = "build.rs"


[dependencies]
rust-i18n = "3.1.2"     # Multi-language support    
toml = "0.8.19"         # Settings                  
toml_edit = "0.22.22"   # Config file               
serde_json = "1.0.118"  # ANU API                   
csv = "1.3.0"           # Coin database             
rand = "0.8.5"          # Random number generator   
sha2 = "0.10.8"         # Entropy checksum          
hex = "0.4.3"           # Seed                      
bip39 = "2.1.0"         # Mnemonic                  
regex = "1.11.1"        # Parsing derivation path   
secp256k1 = "0.30.0"    # Extended keys             
bs58 = "0.5.1"          # Extended keys             
ripemd = "0.1.3"        # Addresses derivation      
num-bigint = "0.4.6"    # Child keys                
sha3 = "0.10"           # keccak addresses          
gtk4 = "0.9.3"          # GUI GTK4                  
glib = "0.20.5"         # GUI                       
libadwaita = "0.7.1"    # GUI Theme                 
lazy_static = "1.5.0"   # Multithreading            

# Testing
ed25519-dalek = "2.1.1" # Solana                    
include_dir = "0.7.4"
# gdk-pixbuf = "0.20.4"


[package.metadata.included]
include = ["config/**", "doc/**", "lib/**", "locale/**", "res/**"]

[package.metadata.excluded]
exclude = ["build.rs"]


[[bin]]
name = "QR2M"
path = "src/main.rs"


[lib]
name = "qr2m_lib"
path = "src/lib.rs"