[package]
name = "QR2M"
description = "Quantum Random Rust Mnemonic"
version = "0.1.0"
authors = ["ro0t"]
readme = "README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Default
rand = "0.8.5"
sha2 = "0.10.8"
hex = "0.4.3"
bip39 = "2.0.0"

# Testing
structopt = "0.3.26"
# bitcoin = "0.31.0"
# hmac = "0.12.1"