[package]
name = "QR2M"
description = "Quantum Random Rust Mnemonic"
version = "0.1.1"
authors = ["Control Owl <qr2m[at]r-o0-t[dot]wtf>"]
readme = "README.md"
edition = "2021"


[dependencies]
# Default
rand = "0.8.5"
sha2 = "0.10.8"
hex = "0.4.3"
bip39 = "2.0.0"
structopt = "0.3.26"

# Testing
# bitcoin = "0.31.0"
# hmac = "0.12.1"