[package]
name = "QR2M"
description = "Quantum Random Rust Mnemonic"
version = "0.11.2"
authors = ["Control Owl <qr2m[at]r-o0-t[dot]wtf>"]
# copyright = "Copyright © 2023-2024 D3BUG"
license-file = "LICENSE.txt"
repository = "https://github.com/control-owl/qr2m"
readme = "README.md"
edition = "2021"


# Crate                 # Internal function
[dependencies]
rand = "0.8.5"          # Random number generator   
sha2 = "0.10.8"         # Entropy checksum          
hex = "0.4.3"           # Seed                      
csv = "1.3.0"           # Coin database             
bip39 = "2.0.0"         # Mnemonic                  
gtk4 = "0.8.0"          # GUI GTK4                  
glib = "0.19.0"         # GUI                       
libadwaita = "0.6.0"    # GUI Theme                 
regex = "1.10.3"        # Parsing derivation path   
secp256k1 = "0.29.0"    # Extended keys             
bs58 = "0.5.0"          # Extended keys             
toml = "0.8.12"         # Settings                  
serde_json = "1.0.114"  # ANU API                   
rust-i18n = "3.0.1"     # Multi-language support    


# Testing
ripemd = "0.1.3"
crypto-hash = "0.3.4"
hmac = "0.12.1"
generic-array = "1.0.0"
bitcoin = "0.32.0"
lazy_static = "1.4.0"


# num-bigint = "0.4"
# num-traits = "0.2"
# serde = "1.0.202"

[[bin]]
name = "QR2M"
path = "src/main.rs"

[lib]
name = "qr2m_converters"
path = "src/lib.rs"