[package]
name = "QR2M"
description = "Quantum Random Rust Mnemonic"
version = "0.1.0"
authors = ["ro0t"]
readme = "README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
sha2 = "0.10.8"
bitcoin = "0.31.0"