[advisories]
unmaintained = "all"
yanked = "deny"
ignore = [
    # "RUSTSEC-2020-0071",
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "CC0-1.0",
    "Unicode-3.0",
]
confidence-threshold = 1.0

[[licenses.clarify]]
name = "QR2M"
expression = "MIT"
license-files = [
    { path = "LICENSE.txt", hash = 0x7fb2423e }
]

[bans]
multiple-versions = "allow"

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]