name: Check Linux x86_64 MUSL

on:
  workflow_run:
    workflows: ["Verify GPG Signature"]
    types: 
      - completed
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  standard:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl]
        features: ["offline", "full", "dev"]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y libgtk-4-dev libadwaita-1-dev pkg-config libssl-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          components: clippy rustfmt

      - name: Check code
        run: |
          cargo fmt --
          cargo clippy --no-deps --verbose --locked --features "${{ matrix.features }}" --target ${{ matrix.target }} -- -D warnings

      - name: Build
        run: cargo build --release --features "${{ matrix.features }}"

      - name: Run tests
        run: cargo test --release --locked --verbose --no-fail-fast --features "${{ matrix.features }}"