name: check-test

on:
  push:
    tags:
      - "CHECK"
    branches:
      - "master"

permissions:
  contents: write

jobs:
  check-test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          target: [x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl]
          features: ["", "full"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y libgtk-4-dev libadwaita-1-dev pkg-config libssl-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install additional dependencies
        run: |
          cargo install cargo-audit cargo-deny cargo-outdated
          rustup component add clippy rustfmt

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run cargo check
        run: cargo check --verbose --locked --features "${{ matrix.features }}"

      - name: Run Clippy
        run: cargo clippy --no-deps --verbose --locked --features "${{ matrix.features }}" -- -D warnings

#       - name: Run cargo audit
#         run: cargo audit --deny warnings
# 
#       - name: Run cargo deny
#         run: cargo deny check
# 
#       - name: Check outdated dependencies
#         run: cargo outdated --exit-code 1

      - name: Build
        run: cargo build --features "${{ matrix.features }}"

      - name: Run tests
        run: cargo test --release --locked --verbose --no-fail-fast --features "${{ matrix.features }}"