name: Release Linux x86_64 MUSL

on:
  push:
    branches: [ "musl" ]
  pull_request:
    branches: [ "musl" ]
#  workflow_run:
#    workflows: ["Verify GPG Signature"]
#    types:
#      - completed
#    branches: [ "master" ]

permissions:
  contents: write
  packages: write

jobs:
  standard:
    name: ${{ matrix.features }}-${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-musl ]
#        features: [ "offline", "full", "dev" ]
        features: [ "dev" ]
      fail-fast: false

    env:
      APP_NAME: "QR2M"
      APP_PATH: "target/${{ matrix.target }}/release"
      OUTPUT_DIR: "LAB7041/${{ matrix.target }}"

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Cache cargo dependencies"
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: "Build with Docker"
        run: |
          mkdir -p ${{ env.OUTPUT_DIR }}
          docker run --rm -v ${{ github.workspace }}:/usr/src/app -w /usr/src/app \
            -e APP_NAME="${{ env.APP_NAME }}" \
            -e APP_PATH="${{ env.APP_PATH }}" \
            -e OUTPUT_DIR="${{ env.OUTPUT_DIR }}" \
            -e FEATURES="${{ matrix.features }}" \
            -e TARGET="${{ matrix.target }}" \
            -e OUTPUT="true" \
            rust:alpine /bin/sh /usr/src/app/docker.sh
          echo "Listing output directory on host:"
          ls -l ${{ env.OUTPUT_DIR }}

      - name: "Extract version number"
        run: |
          VERSION_NUMBER=$(head -n 1 Changelog.md | cut -d ':' -f 2- | tr -d ' #version')

          if [[ ! "$VERSION_NUMBER" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: VERSION_NUMBER is not in valid format: ${VERSION_NUMBER}"
            echo "Expected format: 1.2.3"
            exit 1
          fi
          echo "VERSION_NUMBER=${VERSION_NUMBER}" | tee -a $GITHUB_ENV

      - name: "Import GPG key"
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.ACTIONS_KEY }}
          passphrase: ${{ secrets.ACTIONS_PASS }}
          git_user_signingkey: true
          git_commit_gpgsign: false
          git_tag_gpgsign: true

      - name: "Create tag"
        run: |
          git config user.name "${{ env.APP_NAME }}"
          git config user.email "${{ secrets.ACTIONS_EMAIL }}"
          VERSION="v${{ env.VERSION_NUMBER }}"

          echo "Checking if tag $VERSION exists..."
          if ! git rev-parse "$VERSION" >/dev/null 2>&1; then
            echo "Tag $VERSION does not exists. Creating new signed tag"
            if ! git tag -a "$VERSION" -s -m "Release $VERSION"; then
              echo "GPG signing failed"
              exit 1
            fi
              git push origin "$VERSION" || {
                echo "Tag push failed"
                exit 1
              }
              echo "Tag $VERSION created sucessfully."
              git ls-remote --tags origin
            else
              echo "Tag $VERSION already exists, skipping"
          fi

      - name: "Generate signature file"
        run: |
          BIN="${{ env.OUTPUT_DIR }}/${{ env.APP_NAME }}"
          SIG="${{ env.OUTPUT_DIR }}/${{ env.APP_NAME }}-${{ matrix.features }}.sig"

          ls -l ${{ env.OUTPUT_DIR }}
          [ -f "$BIN" ] || { echo "Error: Binary not found at $BIN"; exit 1; }
          
          $BIN & PID=$!
          
          for i in {1..30}; do [ -f "$SIG" ] && break; sleep 1; done
          kill $PID 2>/dev/null || true
          
          ls -l ${{ env.OUTPUT_DIR }}
          [ -f "$SIG" ] || { echo "Error: SIG file not found at $SIG"; exit 1; }
          echo "Signature generated at: $SIG"

      - name: Prepare release files
        run: |
          BIN="${{ env.APP_NAME }}"
          SIG="${{ env.APP_NAME }}-${{ matrix.features }}.sig"
          TAR_FILE="${{ env.APP_NAME }}-${{ env.VERSION_NUMBER }}-${{ matrix.features }}-${{ matrix.target }}.tar.gz"
          
          strip "${{ env.OUTPUT_DIR }}/$BIN" || echo "Warning: strip failed"
          
          tar -czf "$TAR_FILE" \
            -C "${{ env.OUTPUT_DIR }}" "$BIN" "$SIG" \
            -C "${{ github.workspace }}" Changelog.md LICENSE.txt

      - name: "Upload to GitHub Releases"
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ env.OUTPUT_DIR }}/${{ env.APP_NAME }}-${{ env.VERSION_NUMBER }}-${{ matrix.features }}-${{ matrix.target }}.tar.gz
            Changelog.md
            LICENSE.txt
          draft: false
          prerelease: true
          tag_name: v${{ env.VERSION_NUMBER }}