name: Release Linux x86_64 GNU

on:
  workflow_run:
    workflows: ["Verify GPG Signature"]
    types:
      - completed
    branches: [ "master" ]

permissions:
  contents: write
  packages: write

jobs:
  standard:
    name: ${{ matrix.features }}-${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]
        features: ["offline", "full", "dev"]
      fail-fast: false

    env:
      APP_NAME: "QR2M"
      APP_PATH: "target/${{ matrix.target }}/release/"
      SIG_FILE: "${{ matrix.features }}.sig"
      OUTPUT_DIR: "LAB7041/linux-gnu"

    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-4-dev libadwaita-1-dev pkg-config libssl-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          components: clippy rustfmt

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check code
        run: |
          cargo fmt --
          cargo clippy --no-deps --verbose --locked --features "${{ matrix.features }}" --target ${{ matrix.target }} -- -D warnings

      - name: Build
        run: cargo build --release --features "${{ matrix.features }}" --target ${{ matrix.target }}

      - name: Run tests
        run: cargo test --release --locked --verbose --no-fail-fast --features "${{ matrix.features }}" --target ${{ matrix.target }}

      - name: Versioning
        run: |
          VERSION_NUMBER=$(head -n 1 Changelog.md | cut -d ':' -f 2- | tr -d ' #version')
          if [[ ! "$VERSION_NUMBER" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: VERSION_NUMBER is not in valid format: ${VERSION_NUMBER}"
            exit 1
          fi
          echo "VERSION_NUMBER=${VERSION_NUMBER}" | tee -a $GITHUB_ENV

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.ACTIONS_KEY }}
          passphrase: ${{ secrets.ACTIONS_PASS }}
          git_user_signingkey: true
          git_commit_gpgsign: false
          git_tag_gpgsign: true

      - name: Create tag
        env:
          GPG_PRIVATE_KEY: ${{ secrets.ACTIONS_KEY }}
          GPG_KEY_ID: ${{ secrets.ACTIONS_KEY_ID }}
          GPG_PASS: ${{ secrets.ACTIONS_PASS }}
          GPG_MAIL: ${{ secrets.ACTIONS_EMAIL }}
        run: |
          git config user.name "$APP_NAME"
          git config user.email "$GPG_MAIL"
                   
          echo "Checking if tag v${{ env.VERSION_NUMBER }} exists..."
          if ! git rev-parse "v${{ env.VERSION_NUMBER }}" >/dev/null 2>&1; then
            echo "Tag v${{ env.VERSION_NUMBER }} does not exists."
            echo "Creating signed tag v${{ env.VERSION_NUMBER }}..."
            if ! git tag -a "v${{ env.VERSION_NUMBER }}" -s -m "Release v${{ env.VERSION_NUMBER }}"; then
              echo "GPG signing failed"
              exit 1
            fi
              git push origin "v${{ env.VERSION_NUMBER }}" || {
                echo "Tag push failed"
                exit 1
              }
              echo "Tag v${{ env.VERSION_NUMBER }} created sucessfully."
              git ls-remote --tags origin
            else
              echo "Tag v${{ env.VERSION_NUMBER }} already exists, skipping"
          fi

      - name: Signature
        run: |
          if [ ! -f "$APP_PATH/$APP_NAME" ]; then
            echo "Error: Binary not found at $APP_PATH/$APP_NAME"
            exit 1
          fi
          
          "$APP_PATH/$APP_NAME" & PID=$!
          
          for i in {1..30}; do
            [ -f "$APP_NAME-$SIG_FILE" ] && { echo "Signature file created: $APP_NAME-$SIG_FILE"; break; }
            sleep 1
          done

          if [ ! -f "$APP_NAME-$SIG_FILE" ]; then
            echo "Error: SIG file not found at: $APP_NAME-$SIG_FILE"
            kill $PID 2>/dev/null || true
            exit 1
          fi

      - name: Prepare release files
        run: |
          strip target/${{ matrix.target }}/release/$APP_NAME
          mkdir -p $OUTPUT_DIR
          cp target/${{ matrix.target }}/release/$APP_NAME $OUTPUT_DIR/$APP_NAME-${{ env.VERSION_NUMBER }}-${{ matrix.features }}
          cp target/${{ matrix.target }}/release/$APP_NAME-${{ matrix.features }}.sig $OUTPUT_DIR/$APP_NAME-${{ matrix.features }}.sig
          tar -czf $OUTPUT_DIR/$APP_NAME-${{ env.VERSION_NUMBER }}-${{ matrix.features }}-${{ matrix.target }}.tar.gz \
            -C $OUTPUT_DIR \
              $APP_NAME-${{ env.VERSION_NUMBER }}-${{ matrix.features }} \
              $APP_NAME-${{ matrix.features }}.sig \
              Changelog.md \
              LICENSE.txt

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            $OUTPUT_DIR/$APP_NAME-${{ env.VERSION_NUMBER }}-${{ matrix.features }}-${{ matrix.target }}.tar.gz
            Changelog.md
            LICENSE.txt
          draft: false
          prerelease: true
          tag_name: v${{ env.VERSION_NUMBER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}