name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-4-dev libadwaita-1-dev pkg-config
        
    - name: Check GTK installation
      run: pkg-config --modversion gtk4 || echo "GTK4 missing"

    - name: Debug Environment
      run: |
        rustc --version
        cargo --version
        echo $PATH

    - name: Clean Cargo cache
      run: cargo clean

    - name: Build with features
      run: cargo build --verbose --features "v4_18"

    - name: Run tests
      run: cargo test --verbose
