name: Sign Commits

on:
  push:
    branches:
      - master

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          KEY_ID=$(gpg --list-secret-keys --keyid-format=long | grep sec | awk '{print $2}' | cut -d'/' -f2)
          echo "Using GPG Key ID: $KEY_ID"
          echo "GPG_KEY_ID=$KEY_ID" >> $GITHUB_ENV
        shell: bash

      - name: Configure Git for Signing
        run: |
          git config --global user.email "qr2m@r-o0-t.wtf"
          git config --global user.name "QR2M"
          git config --global user.signingkey "$GPG_KEY_ID"
          git config --global commit.gpgSign true
          git config --global gpg.program gpg
          git config --global gpg.format openpgp
          git config --global core.editor true
        shell: bash

      - name: Enable GPG Passphrase Handling
        run: |
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo "use-agent" >> ~/.gnupg/gpg.conf
          gpg-connect-agent reloadagent /bye
        shell: bash

      - name: Sign Last Commit
        run: |
          git config --global gpg.program gpg
          git commit --amend --no-edit -S \
            --gpg-sign="${GPG_KEY_ID}" \
            --gpg-sign-args "--batch --yes --pinentry-mode loopback --passphrase \"${{ secrets.GPG_PASSPHRASE }}\""
        shell: bash

      - name: Force Push Signed Commit
        run: git push --force-with-lease
