name: Verify GPG Signature

on:
  push:
    branches:  [ "master" ]
  pull_request:
    branches:  [ "master" ]

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Import GPG Keys
        run: |
          echo "${{ secrets.GPG_PUBLIC_KEY_CONTROL_OWL }}" | gpg --import --no-tty --batch

      - name: Verify Control Owl GPG Signature
        run: |
          COMMIT_HASH="${{ github.sha }}"
          echo "Checking commit: $COMMIT_HASH"

          if ! git verify-commit "$COMMIT_HASH" > /dev/null 2>&1; then
            echo "Error: Commit $COMMIT_HASH failed basic signature verification!"
            git log -1 --show-signature "$COMMIT_HASH"
            exit 1
          fi

          COMMIT_INFO=$(git log -1 --pretty=format:"%H %G? %GK" HEAD^..HEAD)
          read COMMIT STATUS KEY_ID <<< "$COMMIT_INFO"
          echo "Commit: $COMMIT"
          echo "Status: $STATUS"
          echo "Key ID: $KEY_ID"

          if [ "$KEY_ID" != "${{ secrets.CONTROL_OWL_GPG_KEY_ID }}" ]; then
            echo "Error: Commit $COMMIT is signed with an unknown key: $KEY_ID"
            exit 1
          fi
                