name: Verify GPG Signature
on:
  push:
    branches:  [ "master" ]
  pull_request:
    branches:  [ "master" ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git log --pretty=format:"%H %G?" HEAD^..HEAD | grep -v " G$" && { echo "Unsigned commits detected"; exit 1; } || echo "All commits signed"